### ISSUE TITLE
Blank screen on startup after installation

### ISSUE THREAD

**Issue by sh2515** [Unrud/djpdf#4] opened 2019-06-02 15:11 UTC
After I installed via snap on ubuntu 18.04 all I have is a blank window see image
![Screenshot from 2019-06-02 16-13-18](https://user-images.githubusercontent.com/5173444/58763348-67b0dc80-8551-11e9-903b-e050bdfa98cd.png)
I ran it with the command line ```djpdf``` and got the following
```
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/1000/snap.djpdf', please create it with 0700 permissions.
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/1000/snap.djpdf', please create it with 0700 permissions.
file:///snap/djpdf/7/lib/python3.6/site-packages/PySide2/Qt/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: Failed to initialize QSettings instance. Status code is: 1
file:///snap/djpdf/7/lib/python3.6/site-packages/PySide2/Qt/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: The following application identifiers have not been set: QVector("organizationName", "organizationDomain")
file:///snap/djpdf/7/lib/python3.6/site-packages/PySide2/Qt/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: Failed to initialize QSettings instance. Status code is: 1
file:///snap/djpdf/7/lib/python3.6/site-packages/PySide2/Qt/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: The following application identifiers have not been set: QVector("organizationName", "organizationDomain")
```
Can anyone help please?

**Comment by Unrud** [comment] 2019-06-02 16:53
You have to click the "+" button to add images.

**Comment by sh2515** [comment] 2019-06-02 20:11
Hi
Yes it didn't do anything. Single, double, right clicked.
I have sorted the
```
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/1000/snap.djpdf', please create it with 0700 permissions.
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/1000/snap.djpdf', please create it with 0700 permissions.
```
By adding the folder. But still no luck.

**Comment by Unrud** [comment] 2019-06-02 20:57
> I have sorted the
> 
> ```
> QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/1000/snap.djpdf', please create it with 0700 permissions.
> QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/1000/snap.djpdf', please create it with 0700 permissions.
> ```
> 
> By adding the folder. But still no luck.

These warnings are unrelated and can be ignored.

> Yes it didn't do anything. Single, double, right clicked.

A single click should be enough. I can't reproduce the problem on Ubuntu 18.04.

Please check if the "open dialog" was opened somewhere in the background.  Unfortunately the dialog is not modal in the snap version (a problem with Qt Quick).

**Comment by sh2515** [comment] 2019-06-02 21:29
Okay I will try the flatpak version and update

**Comment by onshisan** [comment] 2019-08-24 17:41
I have exactly the same issue as describe here, also in Ubuntu 18.04...

**Comment by Unrud** [comment] 2020-01-05 15:03
I can reproduce the issue on Lubuntu 19.10.
It seems to be a bug in snap. It uses the document portal to show file dialogs.

Flatpak uses the document portal too but it works on Lubuntu 19.10.
Interestingly, after using the document portal in Flatpak it also starts to work in Snap until the next reboot.

I close the issue, because it's not a bug in djpdf.

**Closed as completed by Unrud** 2020-01-05 15:03 UTC
